# Generated by Django 4.0.6 on 2024-12-06 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remauto_crm_system', '0002_alter_account_groups_alter_account_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active_services',
            field=models.ManyToManyField(blank=True, to='remauto_crm_system.service'),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PROBLEM', 'Problem')], default='NEW', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='update_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
