# Generated by Django 4.0.6 on 2024-12-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remauto_crm_system', '0003_client_active_services_client_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='active_services',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='is_reopened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (10, 'Active'), (20, 'Completed'), (30, 'Cancelled'), (90, 'Deleted')]),
        ),
    ]
