# Generated by Django 4.0.6 on 2024-12-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remauto_crm_system', '0004_remove_client_active_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='reason',
            new_name='note_reason',
        ),
    ]
