# Generated by Django 4.0.6 on 2024-12-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remauto_crm_system', '0005_rename_reason_orderstatus_note_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (10, 'Active'), (20, 'Completed'), (30, 'Cancelled'), (90, 'Deleted')], default=0),
        ),
    ]
