# Generated by Django 4.0.6 on 2024-12-08 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remauto_crm_system', '0006_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
